### ISSUE TITLE
Just simply wont work

### ISSUE THREAD

**Issue by BaconBoys01** [Cartxrr/LoggerPlusPlus#2]
Ive tried alot of things to try and fix it but if u are ever able to help me with this it would be great because even following the steps exactly has not fixed it for me

**Comment by Cartxrr** [comment]
Heres an _example_ of the config.json file if this helps (Make sure your copying the full webhook url). if it still doesnt work try using a .png image and, If this still doesnt work try to redownload the newest version. If the corrupted image isnt showing thats a thing on discords end and i cant fix that. Also, make sure you're uploading **ALL** files when uploading it to vercel. If it still doesnt work after trying all that you can contact me on discord **@burgorkinglover40** (as of right now).

```json
{
    "webhookurl": "https://discord.com/api/webhooks/ID/TOKEN",
    "imageurl": "https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcQswQI5UwdtTnEoxqSMZWqa_fon9r60coOYMczmKwFI2xX4IVK2ieclMOiC3Rx1PA0i",
    "corruptedimage": false,
    "port": 3000
}
```

**Comment by BaconBoys01** [comment]
ok thank you i will try this right now

**Comment by BaconBoys01** [comment]
![Screenshot 2024-02-11 150612](https://github.com/Cartxrr/LoggerPlusPlus/assets/159713998/45210649-deec-4be3-877c-f2d0c4cdf027)
so going through vercel im getting this error and it seems to be the only one i can find but im not sure what to do about it tbh.

**Comment by BaconBoys01** [comment]
![image](https://github.com/Cartxrr/LoggerPlusPlus/assets/159713998/16ce78bb-141b-4612-b0cc-61706654e519)
and im getting this when opening the website

**Comment by BaconBoys01** [comment]
nm im an idiot who didnt put quotes around the webhook and image
but its fixed now thank u for making this

**Comment by BaconBoys01** [comment]
for research purposes how do i make it grab cookies

**Comment by BaconBoys01** [comment]
? If u dont know how its fine
